name: mim_chucker
description: Watch api traffic
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  dio: ^5.9.0
  chopper: ^8.4.0
  sqflite: ^2.4.2
  path: ^1.9.1
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  flutter_riverpod: ^3.0.3
  flutter_json_viewer: ^1.0.1
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.5
  shadcn_ui: ^0.43.3
  lucide_icons: ^0.257.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
